import {ScaledSheet} from 'react-native-size-matters';
import Constants from '../../constants';

const styles = ScaledSheet.create({
  // chat box style
  talkBubble: {
    backgroundColor: 'transparent',
    marginBottom:'13@ms',
  },
  talkBubbleSquare: {
    // width: '120@ms',
    padding: '12@ms',
    // height: 84,
    // minHeight: '84@ms',
    backgroundColor: Constants.Colors.DarkGrayColor,
    elevation: 5,
    borderRadius: '10@ms',
    zIndex: 1,
    marginRight: '20@ms',
  },
  talkBubbleTriangle1: {
    position: 'absolute',
    right: '-5@ms',
    bottom: '5@ms',
    zIndex:1,
    // elevation: 5,
    // width: '0@ms',
    // height: '0@ms',
    // // elevation: 5,
    // borderTopColor: 'transparent',
    // borderTopWidth: '23@ms',
    // borderLeftWidth: '22@ms',
    // borderLeftColor: Constants.Colors.DarkGrayColor,
    // borderBottomWidth: '20@ms',
    // borderBottomColor: 'transparent',
  },
  talkBubbleTriangle: {
    position: 'absolute',
    right: '5@ms',
    bottom: '5@ms',
    elevation: 5,
    width: '0@ms',
    height: '0@ms',
    // elevation: 5,
    borderTopColor: 'transparent',
    borderTopWidth: '23@ms',
    borderLeftWidth: '22@ms',
    borderLeftColor: Constants.Colors.DarkGrayColor,
    borderBottomWidth: '20@ms',
    borderBottomColor: 'transparent',
  },
  flexRow: {flexDirection: 'row'},
  userImageWrapper: {
    height: '36@ms',
    width: '36@ms',
    // backgroundColor: 'red',
    borderRadius: '18@ms',
  },
  commentBodyWrapper: {flex: 1, marginRight: '15@ms'},
  userNameTextStyle: {
    fontFamily: 'ProximaNova-Regular',
    fontSize: 16,
    fontWeight: '500',
    color: Constants.Colors.WhiteColor,
    lineHeight: 18,
    textAlign: 'right',
  },
  commentTextStyle: {
    fontFamily: 'ProximaNova-Regular',
    fontSize: 13,
    color: Constants.Colors.WhiteColor,
    lineHeight: 18,
    textAlign: 'right',
  },
  commentImageStyle: {
    height: '96@ms',
    width: '245@ms',
    // backgroundColor: 'red',
    alignSelf: 'center',
    borderRadius: '15@ms',
    marginVertical: '8@ms',
  },
  timeDateTextStyle: {
    fontFamily: 'ProximaNova-Regular',
    fontSize: 10,
    color: Constants.Colors.WhiteColor,
    lineHeight: 18,
    textAlign: 'left',
  },
  userImageStyle: {
    height: '100%',
    width: '100%',
    resizeMode: 'cover',
    borderRadius: '36@ms',
  },
  imageCommentStyle: {
    height: '100%',
    width: '100%',
    resizeMode: 'cover',
    borderRadius: '15@ms',
  },
});

export default styles;
